<?php
/**
 * WeCodeArt Framework.
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package 	WeCodeArt Framework
 * @subpackage 	Support\Modules\Accordion\has_wp_interactivity
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since 		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Accordion;

defined( 'ABSPATH' ) || exit(); 

use WeCodeArt\Config\Interfaces\Conditional;

/**
 * Conditional that is only met when plugin is active.
 */
class Condition implements Conditional {

	/**
	 * @inheritdoc
	 */
	public function is_met(): bool {
		if( defined( 'GUTENBERG_VERSION' ) ) {
			return version_compare( GUTENBERG_VERSION, '17.0', '>=' );
		}

		$version = $GLOBALS['wp_version'];

		if( str_contains( $version, '-beta' ) || str_contains( $version, '-RC' ) ) {
			$version = current( explode( '-', $version ) );
		}

		return version_compare( $version, '6.5', '>=' );
	}
}